### ISSUE TITLE
Please clarify confusing code. 

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/hedgehog-extras#23]
This is confusing:

https://github.com/input-output-hk/hedgehog-extras/blob/9ea1845ca2036e7a1ae9fcebe393526540c5c233/src/Hedgehog/Extras/Test/Base.hs#L287

Is `let relPath = tempDir <> "/" <> filePath` really what is needed here
or should that actually be `let relPath = tempDir </>  filePath` ?
If not `let relPath = tempDir </>  filePath` please add a comment why.

**Comment by newhoggy** [comment]
Resolved.
