### ISSUE TITLE
Two main/master branches. Please delete one

### ISSUE THREAD

**Issue by erikd** [input-output-hk/hedgehog-extras#47]
This project has both a `main` and a `master` branch which is confusing and caused me to waste time preparing a commit against `master` when it should have been against `main`.

Please delete one or the other. My personal preference would be for the deletion of `main`.

Once they are both up-to-date, one should be deleted, and the other should be set to the default branch.

**Comment by carbolymer** [comment]
`master` is gone. Closing as complete.
